### ISSUE TITLE
Window border detection offset

### ISSUE THREAD

**Issue by Abukes01** [fdibaldassarre/linux-shimeji#6]
I have the program running on Linux Mint and a custom shimeji loaded.

The mascots work fine and their behaviors are read properly, though the window border detection seems to have a bit of a problem, as  the shimejis pass through the panel bar (tested both in the bottom and left-side position), as well as their side-crawling behaviors seem to have a weird Y offset, making them clip through the top of a window, and float below the window when climbing.

Would there be a possibility to add a way to make custom offsets for window detection, like it works in the Windows version, possibly somewhere in the config?

Example of the behavior:
![image](https://github.com/fdibaldassarre/linux-shimeji/assets/51299415/6310f42a-184f-4e9e-bd07-c6873cdb528e)

**Comment by fdibaldassarre** [comment]
Hi,
I added a window.conf file that allows you to configure the offsets.

Install the new version and create a `~/.config/shimeji/window.conf` file with contents
```
0
-130
0
-130
```
It should fix the border detection (experiment with the values).

A proper solution would be to update the project to work with Wayland and modern libraries, but I really don't have time for this...

Thanks,
Francesco

**Comment by Abukes01** [comment]
The solution worked! It's a little buggy here and there, the shimejis sometimes get locked up on a window border or refuse to acknowledge a window is there at all, but it works most of the times.

The offsets that worked for me were:
0
-70
0
-70

I'm running Cinnamon, not Wayland, though support for Wayland would be great somewhere in the future.

Thanks a lot!
Abukes

**Comment by TheCheddarCheese** [comment]
@Abukes01 did that fix the panel issue? my shimeji still doesn't want to acknowledge its existence

**Comment by Abukes01** [comment]
@TheCheddarCheese yeah, it works fine on my end, what distro are you running, and what window manager do you have? May be a problem unrelated to this project.

The windows must be in focus and not overlalpping, the overlap glitches it out from what I noticed and it's sometimes working, and sometimes not.

Also sorry for the late reply

**Comment by TheCheddarCheese** [comment]
> [@TheCheddarCheese](https://github.com/TheCheddarCheese) yeah, it works fine on my end, what distro are you running, and what window manager do you have? May be a problem unrelated to this project.
> 
> The windows must be in focus and not overlalpping, the overlap glitches it out from what I noticed and it's sometimes working, and sometimes not.
> 
> Also sorry for the late reply

The windows aren't the problem, it's the bottom panel. My shimeji phases through it.
(Mint 22.1 with Cinnamon)

![Image](https://github.com/user-attachments/assets/3f1b335e-f972-4b37-99f0-cb0e038cb0a1)
